### ISSUE TITLE
Error when autocomplete

### ISSUE THREAD

**Issue by 6aKa** [SiebelsTim/hack-sublime#12]
Autocomplete add error in console.
<code>
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 359, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "hack in C:\Users\art\AppData\Roaming\Sublime Text 3\Installed Packages\hack-sublime.sublime-package", line 99, in on_query_completions
NameError: global name 'settings' is not defined
</code>

**Comment by SiebelsTim** [comment]
Closed in 569594a
