### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by a1exsnow** [SiebelsTim/hack-sublime#14]
Hi!

While saving file I get this error - console output:

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 553, in run_
    return self.run()
  File "hack in C:\Users\Alex\AppData\Roaming\Sublime Text 3\Installed Packages\Hacklang Typechecker and Autocompletion.sublime-package", line 16, in run
  File "hack in C:\Users\Alex\AppData\Roaming\Sublime Text 3\Installed Packages\Hacklang Typechecker and Autocompletion.sublime-package", line 35, in getOutput
  File "./subprocess.py", line 824, in **init**
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл
unloading plugin Hack.hack
reloading plugin Hack.hack

"Не удается найти указанный файл" means "Can not find specified file"

Thanks

**Comment by SiebelsTim** [comment]
Hi,

how did you setup `hh_client`? There is no Windows support for the hhvm, so I assume you have setup a linux virtual machine. This sublime package allows you to specify ssh connection settings to remotely invoke `hh_client`.

Look into the [README](https://github.com/SiebelsTim/hack-sublime) at the **Windows** section on how to enable invoking hh_client via ssh.

**Comment by a1exsnow** [comment]
yes, i've configured remote hh_client like this:
{
    "hack_ssh_folder": "folder",
    "hack_ssh_address": "user@IP",
    "hack_ssh_enable": true,
}

it's not virtual machine, it's remote server
i've checked hh_client on server - it works fine in that folder

**Comment by SiebelsTim** [comment]
I assume you have input your data into that the parameters. 
Also, does that trailing comma after `hack_ssh_enable` exist? That might be wrong.

**Comment by a1exsnow** [comment]
no, no comma. the whole config is:
{
    "hack_ssh_folder": " **\* ",
    "hack_ssh_address": " **\* @ **\* ",
    "hack_ssh_enable": true,
    "ignored_packages":
    [
        "Vintage"
    ]
}

**\* - represents real data (no whitespaces of course)

**Comment by SiebelsTim** [comment]
Looks like it can't find the `ssh` command. I don't really know how that is working on windows. Can you install ssh on windows, so that the command `ssh` is available? If not I have to search on how to do it with sublime (as I remember, libraries were a pain to setup).

And I just noticed I haven't pushed an update to the package control in a year, which I will fix now :)

**Comment by a1exsnow** [comment]
I've installed `ssh`. And now there is no error. Thanks!
But I also don't see any error from typechecker. I used an example from this docs and when I execute it on server I get error:
`# hh_client`
`test.hh:6:10,12: Invalid return type (Typing[4110])`
`test.hh:5:21,23: This is an int`
`test.hh:6:10,12: It is incompatible with a float`
`test.hh:9:1,7: Remove all toplevel statements except for requires (Parsing[1002])`

But when I press Ctrl+S in Sublime on Windows it connects to server but there is nothing in console. Where I can see an error and how to check if it really gets an error?

**Comment by SiebelsTim** [comment]
Make sure that it triggeres a save, i.e. write some spaces to the file and press Ctrl+S.
Also make sure, that the folder you specified for `hack_ssh_folder` is the correct folder **on the server**.

**Comment by a1exsnow** [comment]
it really triggers and folder is correct. what I see in console is "Waiting for hh_client to initialise..." and that's all

**Comment by SiebelsTim** [comment]
Mh, is it a large codebase? Can you wait a few moments and try again?

**Comment by a1exsnow** [comment]
No. It's just an example from docs. I tried many times - no results...
